### ISSUE TITLE
Notifications-only plasmoid: brainstorm

### ISSUE THREAD

**Issue by star-buck** [plasma-extensions/plasma-widget-notification-sidebar#1]
So a user could place both independently in the panel and invoke each of them.

**Comment by azubieta** [comment]
I'll take the design from the wire frame that @UriHerrera  did for the quick-panel. Please if you have any  correction to make to this let me know.

Besides managing the system notifications will this widget provide any other functionality ?

**Comment by star-buck** [comment]
Lets see after notifications have been implemented if something else is
fitting.

**Comment by azubieta** [comment]
Are we going to have popup notifications? Or all the notifications will be staked at the side pabel?

**Comment by UriHerrera** [comment]
I think both would be a good choice.

**Comment by star-buck** [comment]
I agree.

**Comment by azubieta** [comment]
Here are the first screenshots of the notification panel. I took as base the default notifications plasmoid.
![native_style](https://cloud.githubusercontent.com/assets/1138094/17712753/59dd61c4-63c5-11e6-98a0-d25cd36267c3.png)
![native_style_clear](https://cloud.githubusercontent.com/assets/1138094/17712754/59e69ec4-63c5-11e6-9157-b3daf129d14e.png)

**Comment by azubieta** [comment]
I have finished the port of the notifications applet, please test it.

**Comment by UriHerrera** [comment]
![](http://i.imgur.com/MBgK7e7.png)

Tested. Nice!. Though I don't know why mine is rather big

# 

Ok so things I noticed:
- We should change the icon. I think there's a bell icon in Breeze but if there isn't I can make one.
- Would be cool that there was a notification counter at the top of the icon. e.g. like [this](https://www.viget.com/uploads/image/blog/notifications-square.png).
- It may just be Chrome though but no notifications are shown for Chrome.
- Once the window is open it won't close unless I click on the desktop or I click on the icon in the system tray. A close button would be nice.

# 

_On another note, this is how plasmoids in the system tray should look like. No bottom or sides being cut-off._

**Comment by star-buck** [comment]
Does the widget stack up notifications? And offer a delete all button in
addition to close each notification by hand?

E.g.:
Can I make each song change while listening to radio get stacked again
(persistent) in this widget, or does it just behave like the default
notification widget?

**Comment by azubieta** [comment]
The widget keeps the behavior of the plasma notifications. It stacks only those notifications that doesn't provide an expiration time, otherwise we will end with a thousand of notifications stacked only from the radio player and the browser. Alternatively we could add a configuration entry so the user can decide if he wants to stack all or not.

The widget also provides a "clearAll" button at the bottom left.

The width of the widget right now is 1/4 of the screen width. I do it that way in order to provide a consistent view between different screens. If have any recommendations please let me know.

About the chrome notifications, probably as you say it's a problem of itself. Please check if it shows the notifications with the default notifications widget.

The sidebar hides when it loses focus. But the system panel, by design, never acquires focus. So the sidebar will not be hidden, this also applies for the rest of the panel widgets.

About the bell icon, remember that not only notifications are shown in our side panel but also the system jobs like copy, delete or zipping. Would this approach be consistent with it? Are we going to move the jobs outside the widget?

**Comment by star-buck** [comment]
lets leave the icon as is, if bell doesnt have all the other features mentioned.
As for the stacking:
yes, we need toc hange that behaviour, as the default assumption and implementation is insane (sorry for the harsh word, but it is).
Let's stack all notifications and if possible, also sort them depending on source, like radio, file-related, etc.

**Comment by azubieta** [comment]
Ok, all notifications are being stacked and positioned together attending to the application that create them.

The order is from the most recent one to the oldest.

**Comment by star-buck** [comment]
Did you update the code in master, so we can spin a package?

**Comment by azubieta** [comment]
I'm offline right now. If it hurries I can upload it in a few hours.

**Comment by star-buck** [comment]
What would come out of the current code?

**Comment by azubieta** [comment]
Everything but the "stackAll" and the grouping. I should be able to upload the rest tomorrow or also I can upload a patch. The problem is that i can't connect my pc here and make git push.

**Comment by star-buck** [comment]
@azubieta updating the code would be nice, so we can test.
This goes for all projects, and please update always in master as long as the widgets havent been released as 1.0.

**Comment by azubieta** [comment]
The master branch is up to date with the latest changes: stacking of all notifications and grouping. About the rest of the projects, there are a few things missing:
1- Any of the projects have an specific license I would like to set it.
2- Projects authors
3- Contact info
About the tests we can prepare a set of test cases (also some unitests) for each project and spread it among the potential users.

**Comment by star-buck** [comment]
1. GPLv3+ or later
2. copyright Blue Systems GmbH
3. your name+email if you like
